version: 1.0.{build}
clone_depth: 1
skip_tags: true
environment:
  matrix:
  - IS_FXSERVER: 0
    APPVEYOR_BUILD_WORKER_CLOUD: OMNITRON
    APPVEYOR_BUILD_WORKER_IMAGE: Windows20200507
  - IS_FXSERVER: 1
    APPVEYOR_BUILD_WORKER_CLOUD: OMNITRON
    APPVEYOR_BUILD_WORKER_IMAGE: Windows20200507
    
build_script:
#################
# windows steps #
#################
- ps: git config core.symlinks true
- ps: git reset --hard
- ps: Install-Product node 12 x64
- ps: .\code\tools\ci\build.ps1 -DontUpload $true -SaveDir C:\save

artifacts:
- path: caches/